### ISSUE TITLE
Problem with playing too many roles in nested contexts

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#10]
``` java
class Person {
    public Person(String name) {
        name_ = name;
    }

    public String name() const {
        return name_;
    }

    private String name_;
}

context CleanTable {
    role Waiter {} requires {
        String name() const;
    }

    // Nice duck typing feature :)
    public CleanTable(Waiter person) {
        Waiter = person;
    }

    public void clean() {
        System.out.println(Waiter.name() + " is cleaning the table.");
    }
}

context WaitTable {
    role Waiter {
        public void waitForGuestsToFinish() {
            new CleanTable(this).clean();
        }
    } requires {
        String name() const;
    }

    public WaitTable(Person person) {
        Waiter = person;
    }

    public void start() {
        Waiter.waitForGuestsToFinish();
    }
}

{
    Person p = new Person("Jeeves");
    new WaitTable(p).start();
}
```

Full output:

```
___________________________________________________________
Object of type Person playing too many roles, including Waiter
    In Context WaitTable: Waiter.
    In Context CleanTable: Waiter.
Jeeves is cleaning the table.
```

I was surprised this wasn't allowed? Isn't the outer Context put on hold while the other one executes?

**Comment by jcoplien** [comment]
> Den 18/12/2015 kl. 03.21 skrev Andreas notifications@github.com:
> 
> I was surprised this wasn't allowed? Isn't the outer Context put on hold while the other one executes?

When I implemented this, I knew that it would raise eyebrows and that it would be difficult to describe. But I think that it is exactly the right behaviour.

Think of it this way: what if CleanTable modified some state of Person on which WaitTable depended? Let’s say that in CleanTable, the clean method put an apron in the waiter. That isn’t very becoming of a waiter who is also playing the role of Waiter in the WaitTable Context. It becomes a surprise, a side-effect on the object that I am unable to reason about from within the WaitTable Context.

It’s of course O.K. if the second Context doesn’t do anything that would disable the Role-player from carrying out its Role in the current Context. If the second Context doesn’t modify the state of the Role-player then it can be guaranteed to be safe. And that’s why Stage Props exist.

Right now I think the environment just barks at you if it finds an object playing multiple Roles — I think it nonetheless goes ahead and does what you ask. Maybe there should be a language feature that enables you to tell the compiler “I know what I’m doing” so that a given object is allowed to play multiple Roles concurrently. I’m not sure. It takes out out of the realm of simplicity. But I’m not sure that is a property of the object, or if one or the other Role signifies the other Roles that the object may concurrently play. It may be different for different Role-players. I’m interested in your ideas on this. I’m copying the list to get broader feedback.

I see that earlier you posted the bug to the object-composition group that elicited the “Object of type Note playing too many roles, including LowNote” error, even though the Role-player was only playing Stage Props. I believe that has been fixed.

By the way, you should be very proud of your code. It’s nice to see the language features actually used, and used so insightedly. You know you’re the first person in the world who’s actually doing this in a language designed exactly for this purpose! We should get some of your code up on fulloo.info — maybe the chord identifier code once it’s tidied up.

I have on my list to chase down a whole bunch of other “little” bugs you’ve found — like the problems with logical negation, another problem you mentioned with using integers (so you were forced to use floats), a problem with rich boolean expressions in assert arguments, etc. I expect it will take about two or three months of continued effort to get through the alpha release stage and get to the point where we can honestly call this a beta. At that point I hope people start digging into the code and sending me pull requests for their branches (hint, hint, Matt…)

As for right now, I’m happy to have people add test examples. The more, the merrier. I’ll delete them if I find them totally unusable but almost every new piece of code tortures the environment in a new way. To add a test, just put it in the tests/ folder with a .k suffix. Then go into info.fulloo.trygve.editor and it to the list of test files in TestRunner.java. Please do this only for examples that work. Bug examples should be sent directly to me.

(By the way, when you send me code via Email, all the periods are elided ;-) I can usually figure them out from context, and I’ve re-inserted them below.)

class Person {
    public Person(String name) {
        name_ = name;
    }

```
public String name() const {
    return name_;
}

private String name_;
```

}

context CleanTable {
    role Waiter {} requires {
        String name() const;
    }

```
// Nice duck typing feature :)
public CleanTable(Waiter person) {
    Waiter = person;
}

public void clean() {
    System.out.println(Waiter.name() + " is cleaning the table");
}
```

}

context WaitTable {
    role Waiter {
        public void waitForGuestsToFinish() {
            new CleanTable(this).clean();
        }
    } requires {
        String name() const;
    }

```
public WaitTable(Person person) {
    Waiter = person;
}

public void start() {
    Waiter.waitForGuestsToFinish();
}
```

}

{
    Person p = new Person("Jeeves");
    new WaitTable(p).start();
}
Full output:

---

Object of type Person playing too many roles, including Waiter
    In Context WaitTable: Waiter
    In Context CleanTable: Waiter
Jeeves is cleaning the table

**Comment by jcoplien** [comment]
This is really interesting! I see the logic, and stage props is such a
clever way of helping the programmer.

It reminds me somewhat of a C# compiler discussion, where someone wanted
classes to be sealed by default. That makes me think that unless you really
understand DCI, are you going to create roles instead of stage props, and
later, perhaps even after you published a library, you realize the mistake?
Some kind of "stage prop/const by default" could help the programmer here,
a hint to think before modifying state. Does it make sense?

I'm really with you on keeping it simple, thinking about the probability
that people will tell the compiler "I know what I'm doing", but don't
understand the simple way of doing things (abusing the tool).

I'd really like trygve to help people programming, not just giving them
full freedom and see them jump right back in the old paradigm, because of
laziness, unaware about it, or something else. Quoting Alexander from The
Phenomenon of Life, p. 293:

"Among natural phenomena, the fifteen properties seem to appear,
pervasively, in almost _everything_. Yet among human artifacts, the fifteen
properties appear only in the *good *ones. How can the very same properties
be marks of *good *structure in human artifacts, and yet be present in
*all *of nature? What is it about nature which always makes its structures
"good"?

The essence of the problem is that we have not, as far as I know, ever yet
concentrated our attention on the fact that in nature, _all *the
configurations that do occur belong to a relatively small subset of *all *the
configurations that *could possibly_ occur. It is that which permits, I
believe, the characterization of a certain class of structures as living
structure."

Can we use this concept in trygve? It'll take some thinking for sure. As
you said, where is the "decider" that an object can play multiple Roles
concurrently? I'm thinking about the good old Money Transfer. It will
obviously mutate state, does it mean that the Account objects can't be used
anywhere else in their parent Context, or in some places? What places? What
about long-running Contexts?

Thanks for your kind words about my code. It took a few years to get there,
starting from the first time I read the article on Artima. :) Putting some
examples up on fulloo.info would be nice. Oh, about sending code via email,
I'm using github to open issues and send code there. If you open the issue
there instead, you can copy and paste the code as it should be. But I can
put them up on a git branch too, as I've done with the chord identifier.
I'm enjoying this, it'll be a couple of fun months ahead!

/Andreas

fre 18 dec. 2015 kl 12:33 skrev James O Coplien cope@gertrudandcope.com:

> Den 18/12/2015 kl. 03.21 skrev Andreas notifications@github.com:
> 
> I was surprised this wasn't allowed? Isn't the outer Context put on hold
> while the other one executes?
> 
> When I implemented this, I knew that it would raise eyebrows and that it
> would be difficult to describe. But I think that it is exactly the right
> behaviour.
> 
> Think of it this way: what if CleanTable modified some state of Person on
> which WaitTable depended? Let’s say that in CleanTable, the clean method
> put an apron in the waiter. That isn’t very becoming of a waiter who is
> also playing the role of Waiter in the WaitTable Context. It becomes a
> surprise, a side-effect on the object that I am unable to reason about from
> within the WaitTable Context.
> 
> It’s of course O.K. if the second Context doesn’t do anything that would
> disable the Role-player from carrying out its Role in the current Context.
> If the second Context doesn’t modify the state of the Role-player then it
> can be guaranteed to be safe. And that’s why Stage Props exist.
> 
> Right now I think the environment just barks at you if it finds an object
> playing multiple Roles — I think it nonetheless goes ahead and does what
> you ask. *Maybe there should be a language feature that enables you to
> tell the compiler “I know what I’m doing” so that a given object is allowed
> to play multiple Roles concurrently. *I’m not sure. It takes out out of
> the realm of simplicity. But I’m not sure that is a property of the object,
> or if one or the other Role signifies the other Roles that the object may
> concurrently play. It may be different for different Role-players. I’m
> interested in your ideas on this. I’m copying the list to get broader
> feedback.
> 
> I see that earlier you posted the bug to the object-composition group that
> elicited the “Object of type Note playing too many roles, including
> LowNote” error, even though the Role-player was only playing Stage Props.
> I believe that has been fixed.
> 
> By the way, you should be very proud of your code. It’s nice to see the
> language features actually used, and used so insightedly. You know you’re
> the first person in the world who’s actually doing this in a language
> designed exactly for this purpose! We should get some of your code up on
> fulloo.info — maybe the chord identifier code once it’s tidied up.
> 
> I have on my list to chase down a whole bunch of other “little” bugs
> you’ve found — like the problems with logical negation, another problem you
> mentioned with using integers (so you were forced to use floats), a problem
> with rich boolean expressions in assert arguments, etc. I expect it will
> take about two or three months of continued effort to get through the alpha
> release stage and get to the point where we can honestly call this a beta.
> At that point I hope people start digging into the code and sending me pull
> requests for their branches (hint, hint, Matt…)
> 
> As for right now, I’m happy to have people add test examples. The more,
> the merrier. I’ll delete them if I find them totally unusable but almost
> every new piece of code tortures the environment in a new way. To add a
> test, just put it in the tests/ folder with a .k suffix. Then go into
> info.fulloo.trygve.editor and it to the list of test files in
> TestRunner.java. Please do this only for examples that work. Bug examples
> should be sent directly to me.
> 
> (By the way, when you send me code via Email, all the periods are elided
> ;-) I can usually figure them out from context, and I’ve re-inserted them
> below.)
> 
> class Person {
>     public Person(String name) {
>         name_ = name;
>     }
> 
> ```
> public String name() const {
>     return name_;
> }
> 
> private String name_;
> ```
> 
> }
> 
> context CleanTable {
>     role Waiter {} requires {
>         String name() const;
>     }
> 
> ```
> // Nice duck typing feature :)
> public CleanTable(Waiter person) {
>     Waiter = person;
> }
> 
> public void clean() {
>     System.out.println(Waiter.name() + " is cleaning the table");
> }
> ```
> 
> }
> 
> context WaitTable {
>     role Waiter {
>         public void waitForGuestsToFinish() {
>             new CleanTable(this).clean();
>         }
>     } requires {
>         String name() const;
>     }
> 
> ```
> public WaitTable(Person person) {
>     Waiter = person;
> }
> 
> public void start() {
>     Waiter.waitForGuestsToFinish();
> }
> ```
> 
> }
> 
> {
>     Person p = new Person("Jeeves");
>     new WaitTable(p).start();
> }
> 
> Full output:
> 
> ---
> 
> Object of type Person playing too many roles, including Waiter
>     In Context WaitTable: Waiter
>     In Context CleanTable: Waiter
> Jeeves is cleaning the table
> 
> ## 
> 
> You received this message because you are subscribed to the Google Groups
> "object-composition" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to object-composition+unsubscribe@googlegroups.com.
> To post to this group, send email to object-composition@googlegroups.com.
> Visit this group at https://groups.google.com/group/object-composition.
> For more options, visit https://groups.google.com/d/optout.

**Comment by ciscoheat** [comment]
Hmm, I think I just broke github. I was supposed to be the author of the previous message. :)

**Comment by ciscoheat** [comment]
Closing this since [the discussion](https://groups.google.com/forum/#!topic/object-composition/egqLcUzPyr8) went to the object-composition list.
