### ISSUE TITLE
Role vector: `lastIndex` and `index` are not initialized when vector is empty.

### ISSUE THREAD

**Issue by hvaldecantos** [jcoplien/trygve#100]
I can't find a way to know whether a role vector player is empty or not. In the following example, when the list is empty and I try to use `lastIndex` or `index` it results in a java.lang.NullPointerException.

``` trygve
context Context {
    public Context(List<String> ls) {
        Listing = ls;
    } 

    role [] Listing {
        public void prints_lengths() {
            System.out.print("index: ").println(index); // java.lang.NullPointerException when ls is empty
            System.out.print("lastIndex: ").println(lastIndex); // java.lang.NullPointerException when ls is empty
            for(int i = 0; i <= lastIndex; i++)
               System.out.println(Listing[i].length()); 
        }
    } requires {
        public int length() const;
    }
    public void run() {
        Listing.prints_lengths()
    }
}
{
    List<String> ls = new List<String>();
    // ls.add("1"); ls .add("22"); ls .add("333");
    (new Context(ls)).run()
    System.out.println("End")
}
```

Using trygve 1.6.14
BTW, in trygve manual it is said that "The lastIndex keyword is valid only inside a Role vector script, and designates the number of elements in the vector" (p. 47) when it designates the last possible index.

**Comment by jcoplien** [comment]
The environment now issues a diagnostic. In fact it’s not “index” and “lastIndex” that are giving the problems, but the fact that you can invoke a Role method at all without it being bound to an object. I could detect that condition earlier in execution, but at some cost, so decided to resolve the issue by catching any attempt by the Role method code to access its Role-player.

This example begs a bit more thought about further restrictions on the use of Role vectors. Good Role vector code should be limited in its ability to reason about the vector as a whole or perhaps even to know that the Role is in fact part of a Role vector.

I updated the user manual as well; thanks.

All tests pass and FindBugs is clean.

**Comment by hvaldecantos** [comment]
So, my question is why should the binding fail? Just because the object is an empty list?
Why this object is not capable of playing a Role vector? Doesn't it fulfill the role requirements?!

An empty list is not able to carry out the role because it has no elements, which element has the ability of playing `public int length() const;`? None, because there is no elements in the vector. Therefore, shouldn't the message say something like this:

```
line 6: Roles in `Listing' cannot be played by objects of type `Null':
line 6:     `length()' needed by Role `Listing' does not appear in interface of `Null'.
```

IMHO, this would be thinking the role vector as a whole.

Things get tough when using an array. We are still having the same problem as with the `List`. But, there's more, like this:

```
context Context {
    public Context(String [] ls) {
        RoleVector = ls;
    } 
    ...
}
{
    String [] ls = new String[3];
    ls[0]= "1"; ls[1] = "22";
    (new Context(ls)).run();
}
```

In this case, we have a partially able role-player, there are some role elements that are able to play the role, but not as a whole because there's still a null object.

**Comment by jcoplien** [comment]
> Den 22/03/2016 kl. 23.41 skrev Héctor Adrián Valdecantos notifications@github.com:
> 
> So, my question is why should the binding fail? Just because the object is an empty list?
> Why this object is not capable of playing a Role vector? Doesn't it fulfill the role requirements?!

There is no object.

> An empty list is not able to carry out the role because it has no elements, which element has the ability of playing public int length() const;?
> 
> The list is not the object; it contains the objects.

I think you are confusing two situations. Consider the following four alternatives:

// compile-time legal, but of questionable run-time semantics

context C {
    role [] Role { … }
    public C(Object o) {
       Role = o
   }
}

{
   Object roleplayer = new Object();
   C c = new C(roleplayer)
}

———————

// legal, straightforward semantics

context C {
    role Role { … }
    public C(Object o) {
       Role = o
   }
}

{
   Object roleplayer = new Object();
   C c = new C(roleplayer)
}

———————

// legal, each vector element plays Role (e.g., in turn)

context C {
    role [] Role { … }
    public C(List<Object> o) {
       Role = o
   }
}

{
   Object roleplayer = new List<Object>();
   C c = new C(roleplayer)
}

———————

// legal, Role is played by a single vector object

context C {
    role Role { … }
    public C(Object o) {
       Role = o
   }
}

{
   Object roleplayer = new List<Object>();
   C c = new C(roleplayer)
}

Looking at your style of programming I became a bit worried that you were failing to realise that there is actually a distinction between these cases, which was the reason for my earlier annotation on this ticket. The things that you were doing individually need to be retained in the language (e.g., accessing a Role vector using vector syntax) but they kind of went against the intent of the feature in the setting where they were being used.

As an exercise, play with the requires clauses on the above Roles and see how they need to change according to the situation.

> None, because there is no elements in the vector. Therefore, shouldn't the message say something like this:
> 
> line 6: Roles in `Listing' cannot be played by objects of type`Null':
> line 6:     `length()' needed by Role`Listing' does not appear in interface of `Null’.
> There are no instances of null in your example, so the error message would be misleading
> 
> IMHO, this would be thinking the role vector as a whole.
> 
> See above.

Maybe the tutorial needs a more compelling Role vector example. Its typical use would be in a routing algorithm where one of the Roles is Node. In any given invocation Node is played by a single object but there is an unbounded number of them, one of which, at different times during the algorithm, we choose to address as a Node.

There are a lot of interesting forces at work here such as balancing the need for a Role to be stateless, along with the need of a Role to know its position in a Role vector (so it is a constant property rather than a state).

> Things get tough when using an array. We are still having the same problem as with the List. But, there's more, like this:
> 
> context Context {
>     public Context(String [] ls) {
>         RoleVector = ls;
>     } 
>     ...
> }
> {
>     String [] ls = new String[3];
>     ls[0]= "1"; ls[1] = "22";
>     (new Context(ls)).run();
> }
> In this case, we have a partially able role-player, there are some role elements that are able to play the role, but not as a whole because there's still a null object.

If I understand you, the two situations are identical and, in fact, they are handled by the same code inside the system. The only way in which they differ is that, in this case, there actually is an unitialized value in the “empty” slot in the array. I’ll check the code and put in some better diagnostics if it doesn’t flag this (at run time) already. (BTW, null is a value and not an object — and it is a perfectly valid Role-player. But in this case the vector element has not been initialized even to null. Maybe it should be).

**Comment by hvaldecantos** [comment]
**Case 1:**
Trygve cannot bind the role-player to the role `Role`. This is a role vector and it needs an iterable role-player object type. Run-time message:

```
 Argument `<object of type Object>' is not of an iterable type (List or vector) suitable to playing Role `Role'.
```

**Case 2:**
The object is bound to role `Role`, i.e. the `roleplayer` object is ready to play role `Role`.

**Case 3:**
There's a compilation error:

```
No matching constructor on class `C' for `new' invocation.
```

I think that the intended code should have been (correct me if I'm wrong):

```
context C {
    role [] Role { }
    public C(List<Object> o) { Role = o }
}
{
    List<Object> roleplayer = new List<Object>();
    C c = new C(roleplayer)
}
```

The object of an iterable type is bound to role `Role` and it is ready to play its role.

**Case 4:**
The role `Role` doesn't require an iterable role player. I think that the intended code should have been (correct me if I'm wrong):

```
context C {
    role Role { }
    public C(List<Object> o) { Role = o }
}
{
    List<Object> roleplayer = new List<Object>();
    C c = new C(roleplayer)
}
```

The object of type List is the role-player, and it doesn't require to be of an iterable type. 

---

We can summarize the ability of an object to play a role or a role vector:

|  | role | role[] |
| --- | --- | --- |
| non-iterable object | yes | no |
| iterable object | yes | yes |

There are big differences between these cases in who is the role-player and what is the requirement to play the role. The declaration `role []` imposes that the role-player should be an iterable, but says nothing about the role-player elements in the collection, but the require clauses do. It feels like having two different kind of bindings, one for the iterable object and one for the objects in the collection. Only when using `lastIndex`, `index`, or trying to access role-player elements we can discover if they've been properly bound to a role-player object or if they don't exist at all. Then, as a programmer, we have to check first if the collection is not empty or has an empty slot, before trying to make an object play a role vector.

> Looking at your style of programming I became a bit worried that you were failing to realise that there is actually a distinction between these cases, which was the reason for my earlier annotation on this ticket. The things that you were doing individually need to be retained in the language (e.g., accessing a Role vector using vector syntax)

Is there other way? I know I can cue a role script with an index, and then work in the cued script with the proper role-player element.

> There are a lot of interesting forces at work here such as balancing the need for a Role to be stateless, along with the need of a Role to know its position in a Role vector (so it is a constant property rather than a state).

Regarding the statelessness of roles, I don't see the keywords `index` and `lastIndex` as part of the role each element plays because we can't do `Role[i].lastindex`. I perceive this constant property as outside the role. It would be more stateless if `index` keyword value get unset between cues.

Should I close this issue or leave it open?

**Comment by jcoplien** [comment]
Héctor,

Thanks for ferreting out the bugs in my examples and seeing your way through them ;-)

> Den 24/03/2016 kl. 01.57 skrev Héctor Adrián Valdecantos notifications@github.com:
> 
> There are big differences between these cases in who is the role-player and what is the requirement to play the role. The declaration role [] imposes that the role-player should be an iterable, but says nothing about the role-player elements in the collection, but the require clauses do. It feels like having two different kind of bindings, one for the iterable object and one for the objects in the collection.

That’s because they _are_ two different kinds of bindings.

> Only when using lastIndex, index, or trying to access role-player elements we can discover if they've been properly bound to a role-player object or if they don't exist at all.

Right. To do the alternative (e.g., to detect this at compile time) is provably an NP-hard problem, unless we reduce Role / object bindings to essentially what are class object references to class objects. Then it’s not DCI any more. I can detect it earlier at run time (at the time the Role method is dispatched) but it’s computationally expensive and I didn’t think the benefit was worth the cost. It will be caught eventually, anyhow, unless the Role player reduces to something that could be played by the value null — in which case it’s a non-issue, anyhow.

> Then, as a programmer, we have to check first if the collection is not empty or has an empty slot, before trying to make an object play a role vector.

You need to do that with any identifier, whether a List element, a vector element, or a scalar. Why should this be any different?

I think you should close this issue, unless you have a very concrete suggestion of how the language should behave otherwise. You may create a new issue if you have an alternative proposal for how Role vectors should work. I’m more than happy to continue the discussion on that front.

**Comment by hvaldecantos** [comment]
> > Then, as a programmer, we have to check first if the collection is not empty or has an empty slot, before trying to make an object play a role vector.
> 
> You need to do that with any identifier, whether a List element, a vector element, or a scalar. Why should this be any different?

I mean that we cannot check if the iterable is empty within the context where the role vector is declared even though the iterable object has been bound, we have to do that outside the context, in the context enactment block. I think that Keywords `lastIndex` and `index` make role-player object elements exhibit like a split personality, as an element and as an iterable. On the other hand, it is handy; and depending on how we use it (not in my style ;) it reminds me a little bit of pattern matching in functional programming.

**Comment by jcoplien** [comment]
> Den 24/03/2016 kl. 18.10 skrev Héctor Adrián Valdecantos notifications@github.com:
> 
> I mean that we cannot check if the iterable is empty within the context where the role vector is declared even though the iterable object has been bound, we have to do that outside the context,

You can check it inside the Context (e.g., in a Context instance method) but you can’t do it from within an object playing a Role — because that object doesn’t exist… And Roles don’t exist at run time: only objects do. It’s a quirk of the implementation that you can enter the execution of the Role method at all. As I mentioned in the previous mail, it’s an unfortunate falling short of a grand chimera.

**Comment by hvaldecantos** [comment]
> You can check it inside the Context (e.g., in a Context instance method)

Oh, yes, right.

Thanks James for your time and explanations!
