### ISSUE TITLE
Can't call instance method via role identifier

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#12]
I tried the following code, which I expected to work, but got the error "line 4: Method `println' not declared in Role log". Is this by design?

```
context C1 {
    public C1() {
        log = System.out;
        log.println("test");
    }

    role log {
    }
    requires {
        void println(String msg);
    }
}

{
    new C1();
}
```

**Comment by jcoplien** [comment]
Clever.

But it is less than an ideal world.

In the current implementation of the compiler, this is illegal. In general, to make this work, I’d have to have an infinite pass compiler. Right now it’s 4-pass. I could add another pass and handle a lot, but not all such cases. Therefore, for the time being it is illegal. That probably puts some limitations on mutually referential constructs but otherwise is benign.

The programmer, however, is left clueless by the current diagnostic. I will change it to:

line 4: Method `println' not declared in Role`log’.
line 4:     Try moving the declaration of `log' befor the definition of method`C1()'.

in the next version that I push.

**Comment by mbrowne** [comment]
Yes, it works when I move the `log` role to the top of the context, thanks. I would have thought that you needed to parse all the role declarations first anyway to be able to determine whether a call to a role or instance method is valid, but I'm sure there's a good reason it works the way you described...
