### ISSUE TITLE
Possible extraneous line in selfOrganization example?

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#136]
This selfOrganization example is very interesting...

On a more mundane note, this could just be a syntax feature of trygve I'm not familiar with, but it doesn't appear that this line is doing anything, unless it's there for debugging purposes when in debug mode?

https://github.com/jcoplien/trygve/blob/master/examples/selfOrganization.k#L195

And BTW the other example files are using an underscore naming convention rather than camelCase (should be the least of your concerns of course, I just wanted to mention it so you're aware :) ).

**Comment by jcoplien** [comment]
> On Dec 5, 2023, at 01:48, Matt Browne ***@***.***> wrote:
> 
> 
> This selfOrganization example is very interesting...
> 
> On a more mundane note, this could just be a syntax feature of trygve I'm not familiar with, but it doesn't appear that this line is doing anything, unless it's there for debugging purposes when in debug mode?
> 
> https://github.com/jcoplien/trygve/blob/master/examples/selfOrganization.k#L195
> 
A good example that extends the current threads about asynchrony.

If every object were a process, then each object would just loop, continually inspecting and adapting. But we have only one program counter. So, what I do is to ask each object to notify those other objects that care about its location that the object has moved, and that those other objects have to re-evaluate their positions.

That’s what the line is for.

Am I missing something? (I might be).

The program still runs (to completion) and gives “a right answer” if I delete that line. If I just continually iterate over all the objects (like at line 73 or so, Game.play) the objects will eventually converge. (You still need the loop to make sure everyone gets a chance to adjust, even if none of their neighbors have moved, since the distances may not initially be correct. Hmmm. Maybe it suffices o execute that initial loop just once… Or something like that.) What this line does is to pull the adjustments forward, causing all objects to get in line as soon as is possible within a linear time scheduling regimen. So if A, B, and C are watching D, and D moves, we update A, B, and C now instead of just adjusting them next time through the loop. This is a better approximation for real human behavior in the game.

So the answer you get without that line may be different than with the line, though it’s executing a game with different rules — a rule that says that one person moves at a time. This execution model simulates multiple concurrent moves: think of the iterations inside the for loop as happening in parallel, and the revisitations of the loop triggered by the ensuing recursion to be happening shortly afterwards… 

FWIW, I tend to like to think recursively (which goes along with the asynchronous, parallel model) whereas Trygve shuns away from recursion and prefers loops. If you have just the loop at line 73, you’re like Trygve. If you have line 195, you’re like me. On a single Von Neumann machine, you sadly need both — unless you have an underlying virtual machine that simulates concurrency. (The original C++ — called C84 then — ran on such a virtual machine, to give it Simula 67 semantics. I once (back in 2006 or so) wrote a very large C++ program to simulate a pension company’s nightly run, after building such a virtual machine. It’s like programming in magic — though it would be nonsense to use it for production.)

The interesting bit is that this is violently recursive. If A, B and/or C adjust their location, then they need to notify their observers in turn to evaluate their locations, and so forth. The recursion in theory can go nearly as deep as their objects in the graph. The amIMoving responsibiity is there to short-circuit infinite recursion...

> And BTW the other example files are using an underscore naming convention rather than camelCase (should be the least of your concerns of course, I just wanted to mention it so you're aware :) ).
> 
Yeah, I should maybe at least be consistent...

**Comment by mbrowne** [comment]
Ah, I was just confused because of the lack of parentheses after `CurrentPlayer.moved()`, and at that moment I had forgotten that `moved()` has side-effects. In JS if you don't have parentheses then it just returns a reference to the function, but now I remember that in trygve the parentheses are only needed if your call includes arguments. Also, on a different line you included the parentheses, `moved()`, but that's not a flaw IMO but rather my misunderstanding of the syntax—the programmer should be free to use either syntax. I did test it without that line and it seemed to take a little longer to calculate the result, but I wasn't sure if that was just coincidence and hadn't looked into it deeply.

Thanks for the thorough explanation; I'll close the issue now.
