### ISSUE TITLE
Chord segue

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#14]
Moving on without interruption! :) https://raw.githubusercontent.com/ciscoheat/trygve/bugs/bugs/chord_identifier.k

Quick summary:
1. Logical `&&` and `!` doesn't work
2. Some more expression issues
3. Feature requests: `List/Array::join` and `List::remove`
4. The "may hide method" warning is interesting, how to handle it?

**Comment by ciscoheat** [comment]
1 and 2 are done. No rush for nr 3, but any comments about nr 4? I don't see how the RoleObjectInterface can hide a System Operation. Can you access it in the same scope, without referencing to a Role or `this`?

**Comment by jcoplien** [comment]
> Den 23/12/2015 kl. 01.52 skrev Andreas <notifications@github.com <mailto:notifications@github.com>>:
> 
> 3 Feature requests: List/Array::join and List::remove

I’ve started framing out remove, but it’s a pair of template functions (with overloading to boot) and those are always a bit dicey…

I’m a bit disinclined to add join, since it’s not Java native. And I’m very disinclined to add operators to arrays. I might be convinced. How does a Java person do it? (But my prejudices are showing here…)

> 4 The "may hide method" warning is interesting, how to handle it?

It’s just a warning to let you know you’re overloading the identifier. It applies mainly to code that may be in one of the methods of Root (yes, I know you have none) that are invoking name. Right now the question is on the table whether such an invocation should propagate through to the Context in the absence of a Role method by the same name, and until we resolve that in favour of walling off access at the Role boundary, there remains a potential ambiguity. But, like I said, it’s only a warning to make sure you know what you’re doing.

**Comment by ciscoheat** [comment]
Ok, thank you! Java 8 has [String.join](http://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.CharSequence...-) which may be a good solution.

**Comment by ciscoheat** [comment]
Any progress on the problematic expression here https://github.com/jcoplien/trygve/blob/master/tests/chord_identifier7.k#L101

**Comment by jcoplien** [comment]
This is the one bug that has me stumped. I am not even sure at this point whether it’s a bug — it’s that confusing.

For the time being, there’s an easy fix:

return ( hasInterval(3.0) && !hasInterval(4.0) );

It’s a little unsatisfying but it works. Unfortunately, it’s not high on my queue right now because it’s not a show-stopper.

**Comment by jcoplien** [comment]
The "hides method" situations now are caught at a different place and I think the error messages are more clear. Let me know if you have an idea for further improving the error message.

**Comment by jcoplien** [comment]
The only remaining plaint in this item regards adding a join method to List and array. I can kind of appreciate the need. But I think it is important to remain faithful to the Java APIs; any difference between trygve and Java APIs for similarly named library elements may create confusion.

If you can find a suitable API in the Oracle Java core that supports this functionality I'll take it under serious consideration. I want to grow the overall library functionality and am seeking input about what to do next. But I'm very averse to designing / building a competing set of APIs, given that most programmers will bring their Java mental models with them.

**Comment by jcoplien** [comment]
Closed until we have a new direction for these ideas.

**Comment by ciscoheat** [comment]
I suggested String.join earlier, wouldn't that work?

**Comment by jcoplien** [comment]
Ah! OK!

I’m making some library changes right now. I’ll see if I can work it in.

It’s a static. I hate statics. They break all the rules of my compiler and they’re all special cases…

Oh, well….

**Comment by jcoplien** [comment]
OOO, bad mocus…. join appears to require varargs. I’m not eager to put any varargs scripts into trygve. It really complicates overloading logic and would be a lot of work.

**Comment by ciscoheat** [comment]
There's an overload with an iterable as last parameter, instead of varargs: http://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.Iterable-

**Comment by jcoplien** [comment]
So String would have to be iterable for this to work for you?

**Comment by ciscoheat** [comment]
This is how I'd like it:

``` java
List<String> strings = new List<String>(); // or String[], maybe Iterable<String>?
strings.add("a");
strings.add("b");

String joined = String.join("-", strings);
System.out.println(joined); // "a-b"
```
