### ISSUE TITLE
No short-circuit evaluation?

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#29]
``` java
class Test {
    public Test() {}

    public void run() {
        assert(true || fail());
    }

    private boolean fail() {
        assert(false); return true;
    }
}

new Test().run()
```

Gives `Line 9: Assertion failed.`

**Comment by jcoplien** [comment]
Yuk. Snarky little bug. Fixed.

**Comment by jcoplien** [comment]
This was intentional. I am willing to reconsider. I have long viewed this “optimization” as a C-language thing that is reaching too far to optimize performance. How does Smalltalk do this? How about Pascal?

I just don’t imagine it to be in the mental model of a non-computer person that a language would be so anal about performance so as not to finish the job.

**Comment by jcoplien** [comment]
I think Pascal does this right, if one is going to do it at all. http://www.tutorialspoint.com/pascal/pascal_boolean_operators.htm . Is this an important enough problem to bring focus to now?

**Comment by runefs** [comment]
> Den 2. jan. 2016 kl. 18.59 skrev James O. Coplien notifications@github.com:
> 
> not to finish the job
> I guess the mental models on what the job is. My mental model says it's to calculate the result. Which might mean only evaluating the first expression. That is consistent with my model of side effect free expression evaluation. The second expression is simply waste and would never have any benefit of it being evaluated

**Comment by jcoplien** [comment]
> Den 02/01/2016 kl. 21.19 skrev Rune Funch Søltoft notifications@github.com:
> 
> I guess the mental models on what the job is. My mental model says it's to calculate the result. Which might mean only evaluating the first expression. That is consistent with my model of side effect free expression evaluation. The second expression is simply waste and would never have any benefit of it being evaluated

But I think that reflects a programmer mental model that cares about computational efficiency, rather than a problem-solving model. For a computer-naive practitioner failure to evaluate the other expressions (and their concomittant side effects) may be as much or more of a surprise to them than taking the optimization. It smacks too much of magic.

I’d like to agree with you if for no other reason that I want to discourage anyone thinking about side-effects, but given that Pascal seems already to have followed what was my intuition, I’m going to leave things as they are on this issue — for now. Maybe later I’ll do something more in the nature of Pascal, which makes it very explicit (and readable) what is going on. I don’t think anyone is going to award C (and hence C++ and hence Java) top points for readability of their relational expressions…

Ah, the expression mess. For fun, have a look at tests/rightAssociativeSum2.k.

**Comment by jcoplien** [comment]
> Den 04/01/2016 kl. 01.04 skrev James O Coplien jcoplien@gmail.com:
> 
> Ah, the expression mess. For fun, have a look at tests/rightAssociativeSum2.k.

Hint: In the right evaluation context, this is a perfectly legitimate string:

```
+two+++ + ++two+ three
```

**Comment by ciscoheat** [comment]
This may be a little naive example, but I was considering an everyday
reasoning like "if I have money and the fridge is empty, go shopping."
Would you check the fridge even if you discover that your wallet is empty?

mån 4 jan 2016 01:08 James O. Coplien notifications@github.com skrev:

**Comment by jcoplien** [comment]
> Den 04/01/2016 kl. 01.18 skrev Andreas notifications@github.com:
> 
> This may be a little naive example, but I was considering an everyday
> reasoning like "if I have money and the fridge is empty, go shopping."
> Would you check the fridge even if you discover that your wallet is empty?

Why do you stipulate which one must be done first?

A cardinal rule of writing use cases is: Don’t introduce sequence unnecessarily. This is a perfect example. So the use case articulation would be in terms of both conditions, and if we weren’t limited by linear text, it would be communicated in a way that neither comes before the other.

The practical reason for this analysis rule is that introducing sequence constrains the programmer from what might otherwise be a more efficient implementation.

I see DCI as closer to the use case world; we have said so many times. Writing the code according to a sequence stipulates unnecessary conditions on the business process. It introduces invisible business rules. One implicit rule in your example is that my wallet is the only place with money. Maybe there is some in the safe. Maybe there is a use case extension whereby I stop by the ATM to get money on the way. Maybe there is an extension on the extension that I discover that my ATM card is missing. Or that I can’t find my wallet.

If you are really a control freak and want to control the order in which your users do things (insist that they check their wallet before going to the fridge) make it explicit in the code:

```
    if (moneyInWallet()} {
    if (fridgeNeedsSomething()) {
        . . . . 
    }
}
```

The statement

```
if (moneyInWallet() && fridgeNeedsSomething()) {
```

should not, in my opinion, stipulate any ordering by virtue of any fact that there might be some obscure language rule that stipulates left-to-right evaluation. In any case, it is as important to be able to express that we don’t care about the order as that we do care. That’s a human concern and is really fundamental to the mental model. Rune’s argument is closer to a computing efficiency concern. I want the language to express concepts in human terms. Stipulating an ordering not only robs me of being able to say some things about a mental model, but gives the impression that the software is controlling the person’s behaviour (in arbitrarily mandating the order in which they do things). That’s in general considered a bad idea.

The Pascal designers recognized this and, apart from the blocked if approach above, actually made it possible to distinguish between these two situations within the logical operators. I consider the other languages to be either 1. sloppy in their thinking or 2. overly focused on implementation effiiciency for our concerns here.

Ada is the same, and we find the following accompanying advice: “Shortcut operators are used to make the evaluation of parts of boolean expressions conditional: and then, or else. This should never be done to speed up the evaluation (with modern optimizing compilers, it will possibly not have that effect). The correct use is to prevent the evaluation of expressions known to raise an exception.”

And all these languages have exceptions. Note that the following logical operators are _not_ evaluated left-to-right in any language I know of:

```
a == c || d != e && f
```

The order of evaluation is ==, !=, ||, &&.

Yeah, try explaining that to a 7-year-old, while at the same time conveying the importance of partial evaluation.

**Comment by ciscoheat** [comment]
Great explanation. :+1:

**Comment by jcoplien** [comment]
> Den 04/01/2016 kl. 14.47 skrev Andreas notifications@github.com:
> 
> Great explanation. 
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/jcoplien/trygve/issues/29#issuecomment-168679570.
> 
> Thanks.

I’ve actually added a section for “Design rationale” in the .docx file. Might as well keep these somewhere...
