### ISSUE TITLE
Ready for user input?

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#54]
We've discussed this a little before, just want to put it here. A way to input a line from the user would be great.

Java has a couple of ways of doing it. It seems that `System.in` always needs to be wrapped for it to work. For example:

``` java
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
String line = br.readLine();

Scanner scanInput = new Scanner(System.in);
String line = scanInput.nextLine();

Console console = System.console();
String line = console.readLine();
```

This is of course depending on the ratio between simplicity for the trygve environment, and adherence to the Java API, but I'd love to see `String line = System.in.readln("Name: ")`, which could give a prompt in the output window. That's all I need for a text adventure game. :)

**Comment by jcoplien** [comment]
I’ll start thinking about this more, as having an adventure game sounds cool.

Major issues to be surmounted:
1. Getting System.in into the framework, which requires the new type InputStream and a new static variable. Since I just generalized things to add System.err, this shouldn’t be too bad.
2. Figuring out where the input should come from. For now, I’m guessing that we use the transcript window. I need to find out how to assign input to that window. Right now I think the window is disabled from responding to keyboard input so I need to explore how to make that happen, too.
3. Figuring out how to keep this as close as possible to standard Java while still being easy to implement and powerful enough to use. I’m going to start with System.in.read as a minimal viable product, and then inspect and adapt. If it’s easy to implement the Streams library on top of that I think that would be the way to go.

**Comment by jcoplien** [comment]
I'm going to try to push this up in priority. All the infrastructure is there: I just need to learn how to bind the stream to the proper window. That will require me to do some learning in the area of Java GUI stuff.

**Comment by jcoplien** [comment]
Some basic System.in functionality should work now. And there's a very basic Scanner facility that you can use with System.in. It required a new run-time architecture based on Java threads. I could find _no_ working examples of consoles that properly handled both input and output so I'm guessing that most Java users use GUIs and text boxes, and then just use a CR key binding to alert the app when text has been entered.

**Comment by ciscoheat** [comment]
Thanks for your hard work on this, and sorry for all the Java mess, I just read the mail in the group... I'll test it right now, will create separate issues when I find something.
