### ISSUE TITLE
Comparing `this` using `!=` operator

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#55]
I would like to add an assert statement to my Activity class to ensure that an activity does not have a dependency on itself, but I'm getting a compile error. This is important not only for the integrity of the Activity class but also to prevent infinite loops when frontloading. Here is the error I'm getting:

```
line 27: You may not use an object of type 'Activity' as an argument to `!='.
```

Code:

```
class Activity {
    private String name_;
    private int duration_;
    //earliest possible start time for this activity
    private int earlyStart_;
    private List<Activity> dependencies_;

    public Activity(String name, int duration, int earlyStartTime) {
        name_ = name.clone;
        duration_ = duration.clone;
        earlyStart_ = earlyStartTime.clone;
        dependencies_ = new List<Activity>();
    }

    public Activity(String name, int duration, int earlyStartTime, List<Activity> dependencies) {
        //Not supported; copying and pasting for now
        //this(name, duration, earlyStartTime);

        name_ = name.clone;
        duration_ = duration.clone;
        earlyStart_ = earlyStartTime.clone;

        dependencies_ = dependencies;
    }

    public void addDependency(Activity activity) {
        assert(activity != this, "An activity cannot have a dependency on itself");
        dependencies_.add(activity);
    }

    public int earlyFinishTime() {
        return earlyStart_ + duration_;
    }

    public int earlyStartTime() {
        return earlyStart_;
    }

    public void setEarlyStartTime(int time) {
        earlyStart_ = time.clone;
    }

    public String name() {
        return name_;
    }

    public int duration() {
        return duration_;
    }

    public List<Activity> dependencies() {
        return dependencies_;
    }
}
```

**Comment by jcoplien** [comment]
I’ve long been aware of this issue and have been thinking about it, have kind of come to a conclusion, but didn’t want to rush into an implementation prematurely.

We first need to settle the issue of exactly what operators mean exactly what in terms of equality and identity. Do you mean “is the same object” or do you mean “returns true if compareTo returns 0, and false otherwise?”

The compareTo script is used to support all Abelian comparison operators in trygve, where comparison means Abelian comparison instead of identity sameness. For now, it’s a bit of a confused mess, because:

```
name_ == “abc”
```

is an Abelian comparison while:

```
name_ == null
```

is an identity comparison. (The special token null represents the only value in the language — everything else is an object)

So there are a bunch of issues here. The identity versus equality thing I have thought of redressing with new operators === for identity and !== as its inverse. Yuk. In the mean time, if you want Abelian comparison, you’ll need to ensure that Activity publishes a compareTo script. (All built-in Abelian types have this script in their signature.)  But this will report Abelian equality instead of identity, so we’re back to needing to know which one you mean.

Comments welcome.

**Comment by mbrowne** [comment]
In this case I'm concerned about the identity (I think that would be 
sufficient to prevent an infinite loop here, though I'm not 100% sure).

> The identity versus equality thing I have thought of redressing with 
> new operators === for identity and !== as its inverse. Yuk.
> It's a bit yucky but it would solve the problem. Or if you wanted to 
> make it more kid-friendly you could introduce an "is"  keyword, e.g. 
> `name_ is null`.

**Comment by jcoplien** [comment]
> Den 24/01/2016 kl. 00.42 skrev Matt Browne notifications@github.com:
> 
> In this case I'm concerned about the identity (I think that would be 
> sufficient to prevent an infinite loop here, though I'm not 100% sure).
> 
> > The identity versus equality thing I have thought of redressing with 
> > new operators === for identity and !== as its inverse. Yuk.
> > It's a bit yucky but it would solve the problem. Or if you wanted to 
> > make it more kid-friendly you could introduce an "is" keyword, e.g. 
> > `name_ is null`.

I thought of that, too, but the negation is messy...

**Comment by runefs** [comment]
2016-01-24 10:57 GMT+01:00 James O. Coplien notifications@github.com:

> I thought of that, too, but the negation is messy...

isn't ? as in `name_ isn't null´

**Comment by mbrowne** [comment]
Something about having an apostrophe in an operator seems strange to me (maybe it's just bias from my programming experience). In any case, if `is not` works for SQL, why not us? e.g. `name_ is not null`. You wouldn't necessarily need to make the `not` operator available more generally; it could just be for this special case. Or if you want to avoid the space, how about `is-not` or `is_not`? Or isn't without the apostrophe: `isnt`.

**Comment by jcoplien** [comment]
As of 1.6.4 we now have "is", "Is", "isnot", "is not", "IsNot", and "Is Not" operators in the language. That would appear to meet the need expressed here.

**Comment by mbrowne** [comment]
It's working, thanks.

**Comment by jcoplien** [comment]
Thanks, Matt.
