### ISSUE TITLE
Passing role players as parameters

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#65]
I noticed that the following code works in trygve:

```
context C1 {
    role R {
        public void foo() {
            System.out.println("foo");
        }
    }

    public C1(Object o) {
        R = o
        test(R);
    }

    public void test(R x) {
        x.foo();
    }

}

{
    new C1(new Object());
}
```

How do we all feel about this? I think it makes it harder to understand the Context if role methods can be called via an alias rather than the role identifier, but on the other hand I wouldn't want to prohibit this if it would be necessary or useful in some situations. It is ameliorated by the fact that the parameter type has to be the role name for this to work.

**Comment by runefs** [comment]
I think it's object oriented and something I felt bad about not being able to introduce in Marvin. Given that you have to pass the role name as the type. I would feel that most uses are a smell however, why not make it a role method instead of a procedure? There might be valid cases. If this works for generics then I could see more benefit from it

**Comment by jcoplien** [comment]
> Den 07/02/2016 kl. 09.35 skrev Rune Funch Søltoft <notifications@github.com <mailto:notifications@github.com>>:
> 
> I think it's object oriented and something I felt bad about not being able to introduce in Marvin. Given that you have to pass the role name as the type. I would feel that most uses are a smell however, why not make it a role method instead of a procedure? There might be valid cases. If this works for generics then I could see more benefit from it

My thoughts exactly.

Maybe a warning, with advice to use the Role directly?

**Comment by jcoplien** [comment]
Note that to give a warning in the above situation also generates a warning here, and in many other apparently valid settings. I don't think that's a good idea. Any refined formulation of the problem that would admit this and exclude the above?
      
    context Account {
         private List<Amount> test_;
         public void increaseBalance(Amount amount) {
             test_.add(amount);
         }
 
         stageprop Amount {
         }

         public Account() {
            test_ = new List<Amount>()
         }
    }

    {
        Account src = new Account();
        src.increaseBalance(30);
    }

**Comment by mbrowne** [comment]
The use case I was concerned about was when you pass a role player from one method to another within the Context, and access it via a different variable name when doing so. So maybe it could only be a run-time warning since I don't think you'd be able to determine that at compile time. Hmm, I think we need to think about this some more...

**Comment by jcoplien** [comment]
I changed things so that a warning is issued upon finding this — unless the script is a constructor. It’s good documentation to type the Role-player arguments when creating a Context, and because it’s a constructor there’s no danger that the script is called from elsewhere within the same Context object.

In general there probably should never be a declaration of "TYPE x" where TYPE is a Role name. There may be some edge cases, particularly when assign-once semantics of Roles is enforced. So, for now, it's a warning that suggests that the programmer use the Role name directly. (Constructors, as mentioned above, remain the sole exception).

Added a new test, issue65.k, that elicits the warning.

Please re-open this if you find other compelling cases that suggest that we should do something different.

Fix version is 3.14.

**Comment by mbrowne** [comment]
So just to be clear, the way you wrote the Account example above is also not recommended, right? It seems like this is a case where an interface would be more appropriate, rather than using a stageprop merely as a type declaration.

**Comment by jcoplien** [comment]
This one is kind of marginal. It would be nice to know that what the caller is passing is a valid Amount, without constraining it to a concrete type. But it just makes me feel uncomfortable that the code has multiple identifiers of the Role type. Anything that is accorded that type should be bound to the Role itself. There are arguable exceptions, such as this one, which is why it's a warning and not a fatal error.
