### ISSUE TITLE
Character encoding problem with spell checking

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#78]
The current version of [examples/spellcheck.k](https://github.com/jcoplien/trygve/blob/master/examples/spellcheck.k) crashes because of the character encoding. It seems that a UTF-8 file containing non-ascii characters isn't loaded into the editor correctly.

A fix right now is to copy/paste the correct characters to `SpellCheck.Utilities.isDelim` and in the "main" part, and then saving. Then file is then saved in Win-1252 format, and the example works.

UTF-8 support would be nicer though... :)

Attached is a working example: [spellcheck.txt](https://github.com/jcoplien/trygve/files/138701/spellcheck.txt)

**Comment by jcoplien** [comment]
Do you know if this is reproducible on Linux?

I am wont to view it as a Windows bug, and to close it with the recommendation of the work-around you suggest.

That they may document it as working that way doesn’t make it any less of a bug. As a Java programmer I should be insulated from platform dependencies.

**Comment by ciscoheat** [comment]
I'm not using linux in a graphical environment. But maybe someone else watching this does?

**Comment by ciscoheat** [comment]
@egonelbre I suspect you do :)

**Comment by egonelbre** [comment]
The problem is in the default encoding of a system. In Linux/Mac, I suspect it's already UTF-8. In windows it's still Win-1512.

Java doesn't protect you from the platform setting differences (line endings, path delimiter, default encoding etc.).

The fix is to change all file-reading into:

```
// from
new InputStreamReader(new FileReader(pathName))
// to
new InputStreamReader(new FileInputStream(pathName), "UTF-8")
```

In this case changing it in TextEditorGUI was sufficient, but if it's done elsewhere, those should be changed as well.

**Comment by ciscoheat** [comment]
Thanks guys, it works now after 4051c86.

**Comment by jcoplien** [comment]
Thanks, all.

I still think it’s a Microsoft bug.

**Comment by egonelbre** [comment]
It's really not. Of course there is most variance on Windows platforms and it's the only one where you cannot set platform default to UTF-8, because of [legacy code](http://www.siao2.com/2006/10/11/816996.aspx). Anyways, you would get problems with old Linuxes and very old Macs (https://en.wikipedia.org/wiki/Mac_OS_Roman). Or when the person has modified the locale/encoding settings for a system. I suspect there are also some Linux distros that don't have UTF-8 as the default.
