### ISSUE TITLE
Small inconsistent parsing behavior

### ISSUE THREAD

**Issue by hvaldecantos** [jcoplien/trygve#89]
The following two trygve programs are parsed without any warning or error:

```
{
    int a = 1
    a
    List<int> list = new List<int>()
}
```

```
{
    int a = 1
    1
    Date today = new Date()
}
```

Whereas this one is not:

```
{
    int a = 1
    a
    Date today = new Date()
}
/*
___________________________________________________________
line 3: Type a undefined for declaration
line 4: Object `today' is not declared in scope `<unknown>'.
line 4: Type of `void' is incompatible with expression type `Date'.
*/
```

It parses ok if the expression `a` is followed by a semicolon `;`
This behavior might have no repercussions to other parts of the language or might become a nightmare, don't know. I've just perceived it and I wanted to let you know.

**Comment by jcoplien** [comment]
Not inconsistent at all. The first one can recognize List<int> as a type, which provides context for the other productions and disambiguates them (i.e., it can’t be an expression). In the second one 1 is disambiguously a constant and therefore an expression, which also disambiguates the context. In the third one, the second appearance of a is ambiguous (it could be an expression or the start of a declaration, syntactically); the compiler chooses one path down the parse tree, which happens not to be your intention and happens not to be able to support what follows, and can catch it only during semantic analysis. As a casualty of this ambiguity it thinks Date is an identifier rather than a type.

The grammar has no knowledge of what lexical constructs constitute primitive types. To implement this would make the grammar hopelessly context-sensitive, if we are to support user-defined types… “Date” is what’s called an “add-on”. It’s like a plug-in that isn’t one of the built-in types.

Use semicolons.

Not a bug.

> Den 03/03/2016 kl. 22.11 skrev Héctor Adrián Valdecantos notifications@github.com:
> 
> {
>     int a = 1
>     a
>     List<int> list = new List<int>()
> }

access_qualifier : public|private|/_null_/
builtin_type_name : 'int')
type_name : (int)
compound_type_name : type_name ...
constant : 1
abelian_atom : constant
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
identifier_list : JAVA_ID ASSIGN expr
object_decl : access_qualifier compound_type_name identifier_list () ';'
expr_and_decl_list : object_decl
abelian_atom : JAVA_ID (a)
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
expr_and_decl_list : expr_and_decl_list expr
access_qualifier : public|private|/_null_/
builtin_type_name : ('int')
type_name : (int)
type_list : '<' type_name (',' type_name)\* '>'
type_name : JAVA_ID (List<int>)
compound_type_name : type_name ...
builtin_type_name : 'int')
type_name : (int)
type_list : '<' type_name (',' type_name)\* '>'
type_name : JAVA_ID (List<int>)
argument_list : /\* null _/
message : message_name '(' argument_list ')' (List<int>)
expr : [new List<int>]
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
identifier_list : JAVA_ID ASSIGN expr
object_decl : access_qualifier compound_type_name identifier_list () ';'
expr_and_decl_list : expr_and_decl_list object_decl
block : '{' expr_and_decl_list '}'
expr : block
main : expr
access_qualifier : public|private|/_null_/
builtin_type_name : 'int')
type_name : (int)
compound_type_name : type_name ...
constant : 1
abelian_atom : constant
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
identifier_list : JAVA_ID ASSIGN expr
object_decl : access_qualifier compound_type_name identifier_list (a) ';'
expr_and_decl_list : object_decl
abelian_atom : JAVA_ID (a)
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
expr_and_decl_list : expr_and_decl_list expr
access_qualifier : public|private|/_null_/
builtin_type_name : 'int')
type_name : (int)
type_list : '<' type_name (',' type_name)_ '>'
type_name : JAVA_ID (List<int>)
compound_type_name : type_name ...
builtin_type_name : 'int')
type_name : (int)
type_list : '<' type_name (',' type_name)\* '>'
type_name : JAVA_ID (List<int>)
argument_list : /\* null _/
expr : [new List<int>]
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
identifier_list : JAVA_ID ASSIGN expr
object_decl : access_qualifier compound_type_name identifier_list (list) ';'
expr_and_decl_list : expr_and_decl_list object_decl
block : '{' expr_and_decl_list '}'
expr : block
main : expr
access_qualifier : public|private|/_null_/
builtin_type_name : 'int')
type_name : (int)
compound_type_name : type_name ...
constant : 1
abelian_atom : constant
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
identifier_list : JAVA_ID ASSIGN expr
object_decl : access_qualifier compound_type_name identifier_list (a) ';'
expr_and_decl_list : object_decl
abelian_atom : JAVA_ID (a)
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
expr_and_decl_list : expr_and_decl_list expr
access_qualifier : public|private|/_null_/
builtin_type_name : 'int')
type_name : (int)
type_list : '<' type_name (',' type_name)_ '>'
type_name : JAVA_ID (List<int>)
compound_type_name : type_name ...
builtin_type_name : 'int')
type_name : (int)
type_list : '<' type_name (',' type_name)\* '>'
type_name : JAVA_ID (List<int>)
argument_list : /\* null */
expr : [new List<int>]
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
identifier_list : JAVA_ID ASSIGN expr
object_decl : access_qualifier compound_type_name identifier_list (list) ';'
expr_and_decl_list : expr_and_decl_list object_decl
block : '{' expr_and_decl_list '}'
expr : block
main : expr

{
    int a = 1
    a
    Date today = new Date()
}
access_qualifier : public|private|/_null_/
builtin_type_name : 'int')
type_name : (int)
compound_type_name : type_name ...
constant : 1
abelian_atom : constant
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
identifier_list : JAVA_ID ASSIGN expr
object_decl : access_qualifier compound_type_name identifier_list () ';'
expr_and_decl_list : object_decl
access_qualifier : public|private|/_null_/
type_name : JAVA_ID (a)
compound_type_name : type_name ...
identifier_list : JAVA_ID [Date]
object_decl : access_qualifier compound_type_name identifier_list () ';'
expr_and_decl_list : expr_and_decl_list object_decl
abelian_atom : JAVA_ID (today)
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
argument_list : /\* null _/
message : message_name '(' argument_list ')' (Date)
expr : [new Date]
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
abelian_expr : abelian_expr ASSIGN expr
expr : abelian_expr
expr_and_decl_list : expr_and_decl_list expr
block : '{' expr_and_decl_list '}'
expr : block
main : expr
access_qualifier : public|private|/_null_/
builtin_type_name : 'int')
type_name : (int)
compound_type_name : type_name ...
constant : 1
abelian_atom : constant
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
identifier_list : JAVA_ID ASSIGN expr
object_decl : access_qualifier compound_type_name identifier_list (a) ';'
expr_and_decl_list : object_decl
access_qualifier : public|private|/_null_/
type_name : JAVA_ID (a)
compound_type_name : type_name ...
identifier_list : JAVA_ID [Date]
line 3: Type a undefined for declaration
object_decl : access_qualifier compound_type_name identifier_list () ';'
expr_and_decl_list : expr_and_decl_list object_decl
line 4: Object `today' is not declared in scope`<unknown>'.
abelian_atom : JAVA_ID (today)
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
argument_list : /_ null _/
expr : [new Date]
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
line 4: Type of `void' is incompatible with expression type`Date'.
abelian_expr : abelian_expr ASSIGN expr
expr : abelian_expr
expr_and_decl_list : expr_and_decl_list expr
block : '{' expr_and_decl_list '}'
expr : block
main : expr
access_qualifier : public|private|/_null_/
builtin_type_name : 'int')
type_name : (int)
compound_type_name : type_name ...
constant : 1
abelian_atom : constant
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
identifier_list : JAVA_ID ASSIGN expr
object_decl : access_qualifier compound_type_name identifier_list (a) ';'
expr_and_decl_list : object_decl
access_qualifier : public|private|/_null_/
type_name : JAVA_ID (a)
compound_type_name : type_name ...
identifier_list : JAVA_ID [Date]
object_decl : access_qualifier compound_type_name identifier_list () ';'
expr_and_decl_list : expr_and_decl_list object_decl
abelian_atom : JAVA_ID (today)
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
argument_list : /_ null */
expr : [new Date]
abelian_unary_op : abelian_atom
abelian_product : abelian_unary_op 
abelian_expr : abelian_product 
expr : abelian_expr
abelian_expr : abelian_expr ASSIGN expr
expr : abelian_expr
expr_and_decl_list : expr_and_decl_list expr
block : '{' expr_and_decl_list '}'
expr : block
main : expr

---

**Comment by hvaldecantos** [comment]
Interesting. As `List<int>` and `Data` are types I assumed they were recognized the same way. I saw the source code and list class is also an add-on (src/main/java/info/fulloo/trygve/add_ons/ListClass.java), then I think what helps to disambiguate the context is the type parameter. Thanks for the explanation and your time. I miss ruby-like syntax, but I'd better use semicolons and focus on the paradigm, for now :)

**Comment by jcoplien** [comment]
;-)
